### ISSUE TITLE
Unable to send filter notification with OR, AND

### ISSUE THREAD

**Issue by brenramz** [Lanseuo/onesignal-notifications#7]
For python 3, when I'm trying 
**filters = [
Filter.Tag("activeCoverageZone","=", 40),
"OR",
Filter.Tag("activeCoverageZone","=", 41)
]**
is like I didn't filter anything, nevertheless when I try
**filters = [
Filter.Tag("activeCoverageZone","=", 40)
]**
everything is fine.

**Comment by LucasHild** [comment]
This has been fixed in f0d4752.
